[env]
TERM = "xterm-256color"

[font]
size = 12.0

[window]
padding.y = 10
padding.x = 10

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "Hack Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]
